# Default values for fritzbox-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alexxanddr/fritzbox-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
args:
  # print configured metrics to stdout and exit
  collect: false
  # The URL of the FRITZ!Box UI
  gatewayLuaURL: "http://fritz.box"
  # The URL of the FRITZ!Box
  gatewayURL: "http://fritz.box:49000"
  # The address to listen on for HTTP requests.
  listenAddress: "127.0.0.1:9042"
  # The logging level. Can be error, warn, info, debug or trace
  logLevel: "info"
  # The JSON file with the lua metric definitions.
  luaMetricsFile: "metrics-lua.json"
  # The JSON file with the metric definitions.
  metricsFile: "metrics.json"
  # Disable collecting lua metrics
  noLua: false
  # Use the v1 md5 authentication (default) or the v2 pbkdf2 authentication
  sessionAPI: "v1"
  # Verify the tls connection when connecting to the FRITZ!Box
  verifyTLS: false

secret:
  # The username for the FRITZ!Box UPnP service
  username: ""
  # The password for the FRITZ!Box UPnP service
  password: ""
metrics:
  address: 127.0.0.1
  port: 9042
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}
